# Generated by Django 5.0.6 on 2024-05-20 13:06

from django.db import migrations

def create_document_types(apps, schema_editor):
    TypeDocument = apps.get_model('controlReview', 'TypeDocument')
    TypeDocument.objects.create(description='LIBRETA ELECTORAL O DNI')
    TypeDocument.objects.create(description='CARNET DE EXTRANJERIA')
    TypeDocument.objects.create(description='REG. UNICO DE CONTRIBUYENTES')
    TypeDocument.objects.create(description='PASAPORTE')
    TypeDocument.objects.create(description='PART. DE NACIMIENTO-IDENTIDAD')
    TypeDocument.objects.create(description='OTROS')

class Migration(migrations.Migration):
    
    dependencies = [
        ('controlReview', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_document_types)
    ]
