# Generated by Django 5.0.6 on 2024-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0003_alter_remuneration_options_alter_voucher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneration',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
