# Generated by Django 5.0.6 on 2024-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0005_rename_type_document_worker_typedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='totalAportaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='voucher',
            name='totalDescuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='voucher',
            name='totalRemuneraciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='bonificacionNocturna',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='horasExtraSimples',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='horasExtrasDobles',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='horasLaboradas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
