# Generated by Django 5.0.6 on 2024-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0006_voucher_totalaportaciones_voucher_totaldescuentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='netoPagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
