# Generated by Django 5.0.6 on 2024-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0007_voucher_netopagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceiptverification',
            name='deviceType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='bonificacionNocturna',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='horasExtraSimples',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='horasExtrasDobles',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='horasLaboradas',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='codeCUSPP',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='costCenter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pensionScheme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sede',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='situation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='specialSituation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workRegime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
