# Generated by Django 5.0.6 on 2024-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0008_alter_paymentreceiptverification_devicetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remuneration',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
