# Generated by Django 5.0.6 on 2024-05-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0011_paymentreceiptverification_downloadpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='specialSituation',
            field=models.BooleanField(default=False),
        ),
    ]
