# Generated by Django 5.0.6 on 2024-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0012_alter_worker_specialsituation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='admissionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='terminationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
