# Generated by Django 5.0.6 on 2024-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0013_alter_worker_admissiondate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='errorSend',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sentEmail',
            field=models.BooleanField(default=False),
        ),
    ]
