# Generated by Django 5.0.6 on 2024-05-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0016_paymentreceiptverification_ipaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceiptverification',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='controlReview.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='remuneration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='controlReview.remuneration'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='reviewDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
