# Generated by Django 5.0.6 on 2024-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0017_alter_paymentreceiptverification_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='diasLicenciaGoceHaber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
