# Generated by Django 5.0.6 on 2024-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0019_alter_remuneration_duration_alter_remuneration_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
