# Generated by Django 5.0.6 on 2024-05-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0020_alter_voucher_creationdate_alter_voucher_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remuneration',
            name='remunerationType',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlReview.typeremuneration'),
        ),
    ]
