# Generated by Django 5.0.6 on 2024-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0021_alter_remuneration_remunerationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='fechaFinVacaciones',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='fechaInicioVacaciones',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
