# Generated by Django 5.0.6 on 2024-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlReview', '0022_alter_voucher_fechafinvacaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreceiptverification',
            options={'verbose_name': 'Información verificación', 'verbose_name_plural': 'Información verificación'},
        ),
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'verbose_name': 'Estado de registro', 'verbose_name_plural': 'Estados de registros'},
        ),
        migrations.AlterModelOptions(
            name='typedocument',
            options={'verbose_name': 'Tipo documento', 'verbose_name_plural': 'Tipo documentos'},
        ),
        migrations.AlterModelOptions(
            name='typeremuneration',
            options={'verbose_name': 'Tipo remuneración', 'verbose_name_plural': 'Tipo remuneraciones'},
        ),
        migrations.AlterModelOptions(
            name='typeworker',
            options={'verbose_name': 'Tipo trabajador', 'verbose_name_plural': 'Tipo trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='workerposition',
            options={'verbose_name': 'Puesto trabajador', 'verbose_name_plural': 'Puesto trabajadores'},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='bonificacionNocturna',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='diasLicenciaGoceHaber',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
